name: build

on:
  workflow_call:
    outputs:
      review:
        value: ${{ jobs.review.outputs.review }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      review: ${{ steps.llm-detection.outputs.response }}
    steps:
      - name: Checkout workflow script
        uses: actions/checkout@v4
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
        
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: app

      - name: Initialize app directory
        run: |
          sudo mkdir -p /app
          sudo cp -r app/. /app/
          sudo chown -R "$(whoami)" /app

      - name: Get all files in branch
        id: all-files
        working-directory: /app
        run: |
          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          git ls-tree -r --name-only HEAD >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: LLM Detection
        id: llm-detection
        continue-on-error: true
        env:
          DEEPSEEK_API_KEY: ${{ secrets.LLM }}
        run: |
          ls /app
          ls ./
          set -e
          REVIEW=$(python3 llm-detection.py /app)
          echo "response<<EOF" >> "$GITHUB_OUTPUT"
          echo "$REVIEW" >> "$GITHUB_OUTPUT"
          echo "EOF" >> $GITHUB_OUTPUT"

