name: build

on:
  workflow_call:
    outputs:
      review:
        value: ${{ jobs.review.outputs.review }}
    secrets:
      LLM3:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      review: ${{ steps.llm-detection.outputs.review }}
    steps:
      - name: Checkout workflow script
        uses: actions/checkout@v4
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
        
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: app

      - name: Get all files in branch
        id: all-files
        working-directory: app
        run: |
          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          git ls-tree -r --name-only HEAD >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: LLM Detection
        id: llm-detection
        env:
          CODEX_ACCESS_TOKEN: ${{ secrets.LLM3 }}
        run: |
          set -e
          #pip install claude-agent-sdk
          pip install openai-codex
          python3 llm-detection2.py app
          EXIT_CODE=$?

